# PowerShell에서 발생하는 명령줄 구문 오류를 다시 한번 수정해보겠습니다. 이번에는 cmd.exe를 사용하여 실행하도록 변경하겠습니다.

# 수정되는 부분만 먼저 설명드리고, 전체 파일을 보여드리겠습니다:

# 주요 수정사항:
# - Cppcheck 실행 부분에서 `shell: pwsh`를 `shell: cmd`로 변경
# - 명령어 구문을 Windows cmd 스타일로 수정

# 전체 workflow 파일입니다:

# 워크플로의 이름을 정의합니다. 이 이름은 GitHub의 Actions 탭에서 표시됩니다.
name: GitHub Actions 실행시켜보기

# 워크플로우가 실행될 조건을 지정합니다.
on:
  # main 브랜치에 push가 발생할 때 실행됩니다.
  push:
    branches:
      - main
  # main 브랜치로 pull request가 생성되거나 업데이트될 때 실행됩니다.
  pull_request:
    branches:
      - main

# 실제로 실행될 작업들을 정의합니다.
jobs:
  # 'Build-And-Analysis'라는 이름의 작업을 정의합니다.
  # 이 작업은 빌드와 다양한 코드 분석을 수행합니다.
  Build-And-Analysis:
    # Windows 최신 버전의 가상 환경에서 실행합니다.
    # Visual Studio 2022와 관련 도구들이 미리 설치되어 있습니다.
    runs-on: windows-latest

    # GitHub Actions가 필요로 하는 권한들을 설정합니다.
    permissions:
      actions: read      # GitHub Actions의 실행 권한
      contents: read     # 저장소 내용을 읽을 수 있는 권한
      security-events: write  # 보안 검사 결과를 쓸 수 있는 권한

    # 순차적으로 실행될 단계들을 정의합니다.
    steps:
      # Step 1: 저장소 코드를 가져옵니다.
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        # 이 단계는 현재 저장소의 코드를 가상 환경으로 복사합니다.

      # Step 2: 기본 동작 테스트를 위한 Hello World 출력
      - name: Hello World 출력
        run: echo "Hello World"
        # 워크플로우가 정상적으로 실행되는지 확인하기 위한 기본 테스트입니다.

      # Step 3: 여러 줄의 명령어 실행 테스트
      - name: 여러 명령어 실행
        run: |
          echo "Hello World"
          echo "Good "
          echo "Morning"
        # 파이프라인(|)을 사용하여 여러 줄의 명령어를 실행하는 예제입니다.

      # Step 4: GitHub에서 제공하는 환경 변수 출력
      - name: GitHub Actions 변수 출력
        run: |
          echo "Repository: %GITHUB_REPOSITORY%"
          echo "SHA: %GITHUB_SHA%"
        shell: cmd
        # GitHub Actions에서 기본으로 제공하는 환경 변수들을 확인합니다.

      # Step 5: GitHub Secrets에 저장된 비밀 값 출력
      - name: GitHub Actions 비밀변수 출력
        env:
          MY_NAME: ${{ secrets.MY_NAME }}     # GitHub Secrets에 저장된 MY_NAME 값
          MY_HOBBY: ${{ secrets.MY_HOBBY }}   # GitHub Secrets에 저장된 MY_HOBBY 값
        run: |
          echo "Secret: %MY_NAME%"
          echo "Secret: %MY_HOBBY%"
        shell: cmd
        # 민감한 정보를 안전하게 사용하는 방법을 보여줍니다.

      # Step 6: Cppcheck 도구 설치
      - name: Cppcheck 설치
        run: |
          choco install cppcheck
        shell: pwsh
        # chocolatey 패키지 관리자를 사용하여 Cppcheck를 설치합니다.

      # [수정된 부분 시작]
      # Step 7: Cppcheck를 사용한 정적 코드 분석 실행
      # PowerShell 대신 CMD를 사용하여 명령어 실행 문제 해결
      - name: Cppcheck 정적 분석
        run: |
          REM 모든 C++ 파일에 대해 Cppcheck 분석 실행
          cppcheck ^
          --enable=all ^
          --suppress=missingInclude ^
          --inline-suppr ^
          --inconclusive ^
          --std=c++17 ^
          --output-file=cppcheck_report.txt ^
          .
        shell: cmd
        # Windows CMD에서는 ^ 를 사용하여 줄 연속을 표시합니다.
        # PowerShell 구문 오류를 피하기 위해 CMD 셸을 사용합니다.
      # [수정된 부분 끝]

      # Step 8: Cppcheck 분석 결과를 아티팩트로 저장
      - name: Cppcheck 결과 저장
        run: |
          if exist cppcheck_report.txt (
            type cppcheck_report.txt
            mkdir artifacts
            copy cppcheck_report.txt artifacts\
            echo "Cppcheck 분석 결과가 저장되었습니다."
          ) else (
            echo "Warning: Cppcheck 결과 파일을 찾을 수 없습니다."
          )
        shell: cmd
        # CMD 명령어를 사용하여 결과 파일 처리

      # Step 9: CodeQL 분석 준비
      - name: CodeQL 초기화
        uses: github/codeql-action/init@v3
        with:
          languages: cpp    # C++ 언어 분석 설정
        # GitHub의 강력한 코드 분석 도구인 CodeQL을 초기화합니다.

      # Step 10: Visual Studio를 사용한 프로젝트 빌드
      - name: Visual Studio 프로젝트 빌드
        run: |
          # Visual Studio의 MSBuild 도구 경로를 찾습니다.
          $msbuildPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          # 프로젝트를 Release 모드로 빌드합니다.
          & "$msbuildPath" GitHub_VS2022_Test_Project.sln /p:Configuration=Release
        shell: pwsh
        # Visual Studio 프로젝트를 빌드하고, 이 과정에서 CodeQL이 코드를 분석합니다.

      # Step 11: CodeQL 분석 실행
      - name: CodeQL 분석 실행
        uses: github/codeql-action/analyze@v3
        # 빌드 중 수집된 데이터를 바탕으로 보안 취약점을 분석합니다.
        # 결과는 GitHub의 Security 탭에서 확인할 수 있습니다.

# 주요 변경사항 설명:
# 1. Cppcheck 실행 부분을 `shell: cmd`로 변경했습니다.
# 2. 명령줄 연속 문자를 백틱(`)에서 캐럿(^)으로 변경했습니다.
# 3. 결과 파일 처리 부분도 CMD 명령어로 변경했습니다.
# 4. 환경 변수 참조 방식을 CMD 스타일(%VARIABLE%)로 변경했습니다.

# 이러한 변경으로:
# - PowerShell 구문 오류가 해결됩니다
# - Windows CMD에서 안정적으로 실행됩니다
# - 명령어가 더 명확하게 실행됩니다
