# 워크플로의 이름을 정의합니다. 이 이름은 GitHub Actions 탭에 표시됩니다.
name: GitHub Actions 실행시켜보기

# 워크플로가 트리거되는 이벤트를 정의합니다.
on:
  # push 이벤트에 대해 트리거됩니다.
  push:
    # main 브랜치로 푸시될 때만 실행됩니다.
    branches:
      - main
  pull_request:
    branches:
      - main


# 워크플로 실행의 작업을 정의합니다.
jobs:
  # "My-Deloy-Job"이라는 이름의 작업을 정의합니다.
  My-Deloy-Job:
    # 작업이 실행될 가상 환경을 지정합니다. 여기서는 최신 버전의 Windows를 사용합니다.
    runs-on: windows-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    
    # 작업 내에서 실행될 단계들을 정의합니다.
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      # "Hello World 찍기"라는 이름의 단계를 정의합니다.
      - name: Hello World 찍기
        # 이 단계에서 실행할 명령어를 지정합니다. 여기서는 "Hello World"를 출력합니다.
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        # 이 단계에서 실행할 명령어를 지정합니다. 여러 명령어를 세미콜론으로 구분하여 작성합니다.
        run: |
          echo "Hello World"
          echo "Good "
          echo "Morning"
      # Windows에서는 $ENV:환경변수명 형태로 출력해야 함
      - name: GitHub Actions 변수 출력
        run: |
          echo "Repository: $env:GITHUB_REPOSITORY"
          echo "SHA: $env:GITHUB_SHA"

      # 아무한테 노출이 되면 안되는값 출력하기 
      # 비밀변수 등록 업데이트 함 
      - name: GitHub Actions 비밀변수 출력
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
          MY_HOBBY: ${{ secrets.MY_HOBBY }}
        run: |
          echo "Secret: $env:MY_NAME"
          echo "Secret: $env:MY_HOBBY"

      # CodeQL 초기화
      - name: CodeQL 초기화
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      # 솔루션 빌드 (정적 분석 대상이 되는 C++ 빌드)
      - name: Visual Studio 프로젝트 빌드
        run: |
          $msbuildPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          & "$msbuildPath" GitHub_VS2022_Test_Project.sln /p:Configuration=Release
        shell: pwsh

      # CodeQL 정적 분석 실행
      - name: CodeQL 분석 실행
        uses: github/codeql-action/analyze@v3


        



